server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  config:
    activate:
      on-profile: integration

    import:
      - external-integration-config.yml
      - naver-client-config.yml
      - redis-config.yml

logging:
  level:
    org.springframework.boot.context.properties: DEBUG