spring:
  data:
    redis:
      host: ${SERVICE_REDIS_HOST}
      port: ${SERVICE_REDIS_PORT}
      timeout: 3000
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1