version: "3.8"

services:
  redis-auth:
    image: redis:latest
    container_name: redis-auth
    restart: always
    ports:
      - "6379:6379"
    networks:
      - repo-trend-analyze

  redis-service:
    image: redis:latest
    container_name: redis-service
    restart: always
    ports:
      - "6380:6379"
    networks:
      - repo-trend-analyze

#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.5.0
#    container_name: zookeeper
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports:
#      - "2181:2181"
#    networks:
#      - repo-trend-analyze
#
#  kafka:
#    image: confluentinc/cp-kafka:7.5.0
#    container_name: kafka
#    depends_on:
#      - zookeeper
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    networks:
#      - repo-trend-analyze

  auth:
    image: 911kimjonga/repo-trend-auth:latest
    container_name: auth
    restart: always
    env_file: ./.env
    environment:
      - TZ=Asia/Seoul
      - AUTH_REDIS_HOST=redis-auth
      - AUTH_REDIS_PORT=6379
#      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8081:8080"
    depends_on:
      - redis-auth
#      - kafka
    networks:
      - repo-trend-analyze

  integration:
    image: 911kimjonga/repo-trend-integration:latest
    container_name: integration
    restart: always
    env_file: ./.env
    environment:
      - TZ=Asia/Seoul
      - SERVICE_REDIS_HOST=redis-service
      - SERVICE_REDIS_PORT=6379
#      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8082:8080"
    depends_on:
      - redis-service
#      - kafka
    networks:
      - repo-trend-analyze

  messaging:
    image: 911kimjonga/repo-trend-messaging:latest
    container_name: messaging
    restart: always
    env_file: ./.env
    environment:
      - TZ=Asia/Seoul
      - SERVICE_REDIS_HOST=redis-service
      - SERVICE_REDIS_PORT=6379
#      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8083:8080"
    depends_on:
      - redis-service
#      - kafka
    networks:
      - repo-trend-analyze

networks:
  repo-trend-analyze: