version: "3"

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - repo-trend-analyze

  auth:
    image: 911kimjonga/repo-trend-auth:latest
    container_name: auth
    restart: always
    env_file: ./.env
    environment:
      - TZ=Asia/Seoul
      - spring.data.redis.host=redis
    ports:
      - "8081:8080"
    depends_on:
      - redis
    networks:
      - repo-trend-analyze

  integration:
    image: 911kimjonga/repo-trend-integration:latest
    container_name: integration
    restart: always
    env_file: ./.env
    environment:
      - TZ=Asia/Seoul
      - spring.data.redis.host=redis
    ports:
      - "8082:8080"
    depends_on:
      - redis
    networks:
      - repo-trend-analyze

networks:
  repo-trend-analyze: