# 서버
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 스프링
spring:

  config:
    activate:
      on-profile: auth

    import:
      # DB 연결 정보
      - datasource-config.yml
      # JWT 토큰 정보
      - jwt-config.yml
      # Redis 정보
      - redis-config.yml

  # 기타
  autoconfigure:
    # 기본 시큐리티 로그인 비활성화
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# 로깅
logging:
  level:
    root: info