spring:
  datasource:
    # H2 로컬 파일 DB (MySQL 호환 모드)
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10

  # H2 데이터베이스
  h2:
    console:
      enabled: true
      # H2 콘솔 패스
      path: /h2-console
